import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased relative max-w-full overflow-x-hidden`}>
        
        {/* Background Rectangles */}
        <Image
          className='fixed z-0 top-0 right-10'
          src='/images/Rectangle 4 (1).png'
          height={250}
          width={350}
          alt='cube1'
        />
        <Image
          className='fixed top-80 right-60 z-0'
          src='/images/Rectangle 4.png'
          height={250}
          width={350}
          alt='cube2'
        />
        <Image
          className='fixed z-0 top-28 left-10'
          src='/images/Rectangle 5 (1).png'
          height={100}
          width={350}
          alt='cube3'
        />

        {/* Main Content */}
        <div className="relative z-10">
          {children}
        </div>
      </body>
        
    </html>
  );
}
